name: CI
on: pull_request

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  go-check:
    name: Check go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache aqua
        uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.31.0

      - name: gofmt
        run: |
          diff -u <(echo -n) <(go fmt ./...)

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: none

      - name: go test
        run: go test ./... -v

  renovate-lint:
    name: Validate Renovate Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm --entrypoint "bash" -v "${PWD}":/work docker.io/renovate/renovate -c 'cd /work && renovate-config-validator'

  action-lint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1

  e2e-test:
    name: End-to-End testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache aqua
        uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.31.0

      - run: make

      - name: Launch server
        run: |
          ./grpshuffle_server &
          dockerize -wait tcp://localhost:13333          

      - name: Test health
        run: ./grpshuffle_client health --no-tls --host localhost --port 13333 | jq --exit-status

      - name: Test shuffle
        run: ./grpshuffle_client shuffle --no-tls --host localhost --port 13333 --divide 2 chikin-nanban karamen mango jidori | jq --exit-status
