name: Release Node.js

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  pull_request:
    types:
      - closed

defaults:
  run:
    working-directory: node

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/grpshuffle-js/v')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Build
        run: |
          make pack

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
