name: Release prepare Node.js

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: "Next version (ex. 0.0.2)"
        type: string
        required: true
      dry_run:
        description: "When true, publish and commit are not performed."
        type: boolean
        required: false
        default: true

defaults:
  run:
    working-directory: node

jobs:
  release:
    name: Release to npm (dry_run = ${{ github.event.inputs.dry_run }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm version ${{ github.event.inputs.next_version }}

      - name: Setting git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Git Commit
        run: |
          git switch -c releases/grpshuffle-js/v${{ github.event.inputs.next_version }}
          git add package.json
          git commit -m "release (node): grpshuffle-js/v${{ github.event.inputs.next_version }}"
          git tag grpshuffle-js/v${{ github.event.inputs.next_version }}          

      - name: Git Push & Create PR
        if: github.event.inputs.dry_run == 'false' && github.ref == 'refs/heads/main'
        run: |
          git push origin HEAD
          git push origin grpshuffle-js/v${{ github.event.inputs.next_version }}
          gh pr create --title "release (node): grpshuffle-js/v${{ github.event.inputs.next_version }}"
